CREATE TABLE `USER` (
  `ID` varchar(32) NOT NULL,
  `USER_NAME` varchar(128) DEFAULT NULL,
  `PASSWORD` varchar(35) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `WECHAT_ID` varchar(40) DEFAULT NULL,
  `USER_GROUP` varchar(10) NOT NULL,
  `CREATE_TIME` bigint(20) DEFAULT '0',
  `LAST_MODIFY_TIME` bigint(20) DEFAULT '0',
  `IS_DELETED` bit(1) DEFAULT b'0',
  `LAST_VISITED_TIME` mediumtext,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_NAME_UNIQUE` (`USER_NAME`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ORDER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(32) NOT NULL,
  `STATUS` varchar(40) DEFAULT NULL,
  `DELIVER_TIME` bigint(20) DEFAULT '0',
  `COMPLETED_TIME` bigint(20) DEFAULT '0',
  `LAST_MODIFY_TIME` bigint(20) DEFAULT '0',
  `IS_DELETED` bit(1) DEFAULT b'0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ORDER_DETAIL` (
  `ID` varchar(32) NOT NULL,
  `ORDER_ID` bigint(20) NOT NULL,
  `PRODUCT_ID` varchar(40) NOT NULL,
  `QUANTITY` bigint(20) DEFAULT '0',
  `STATUS` varchar(40) DEFAULT NULL,
  `DELIVER_TIME` bigint(20) DEFAULT '0',
  `COMPLETED_TIME` bigint(20) DEFAULT '0',
  `LAST_MODIFY_TIME` bigint(20) DEFAULT '0',
  `IS_DELETED` bit(1) DEFAULT b'0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `USER_INFO` (
  `ID` int(11) NOT NULL,
  `USER_ID` varchar(40) DEFAULT NULL,
  `PHOTO` varchar(70) DEFAULT NULL,
  `ADDRESS` varchar(60) DEFAULT NULL,
  `NICK_NAME` varchar(40) DEFAULT NULL,
  `CREATE_TIME` bigint(20) DEFAULT '0',
  `LAST_MODIFY_TIME` bigint(20) DEFAULT '0',
  `IS_DELETED` bit(1) DEFAULT b'0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `BUYING_CAR` (
  `ID` varchar(32) NOT NULL,
  `USER_ID` varchar(32) NOT NULL,
  `PRODUCT_ID` varchar(40) NOT NULL,
  `QUANTITY` bigint(20) DEFAULT '0',
  `STATUS` varchar(40) DEFAULT NULL,
  `LAST_MODIFY_TIME` bigint(20) DEFAULT '0',
  `IS_DELETED` bit(1) DEFAULT b'0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRODUCT` (
  `ID` varchar(40) NOT NULL,
  `TITLE` varchar(160) DEFAULT NULL,
  `PRODUCT_SEQ` varchar(40) DEFAULT NULL,
  `BROWSE_PATH` varchar(250) NOT NULL,
  `IMAGE_URL` varchar(300) DEFAULT NULL,
  `TYPE` varchar(20) DEFAULT NULL COMMENT 'PARENT, CHILD. NORMAL',
  `PARENT_ID` varchar(40) NOT NULL,
  `QUANTITY` bigint(20) NOT NULL DEFAULT '0',
  `PRICE_INTEGRAL` bigint(20) NOT NULL DEFAULT '0',
  `ATTRIBUTES_TEXT` longtext,
  `ITEM_STATUS` varchar(20) DEFAULT NULL COMMENT 'ACTIVE, INACTIVE. ',
  `CREATE_TIME` bigint(20) DEFAULT '0',
  `LAST_MODIFY_TIME` bigint(20) DEFAULT '0',
  `IS_DELETED` bit(1) DEFAULT b'0',
  `SEARCH_TERMS` mediumtext,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8